services:
  - type: web
    name: parking-system
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --preload
    autoDeploy: true
